name: Build

on: [push, workflow_dispatch]

jobs:
  build-linux:
    name: Build shared libs
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Steamworks SDK
        run: |
          wget -t 5 --retry-connrefused -output sdk135a.zip ${{ secrets.STEAMWORKS_SDK_135A }}
          powershell -command "Expand-Archive -Force '%~dp0sdk135a.zip' '%~dp0'"
          mkdir Steamworks
          move ./sdk/* ./Steamworks
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: dotnet build ./Steamworks.gml 