name: Build

on: [push, workflow_dispatch]

jobs:
  build-linux:
    name: Build for linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Steamworks SDK
        run: |
          sudo curl ${{ secrets.STEAMWORKS_SDK_135A }} --output sdk135a.zip
          sudo apt-get install unzip
          sudo unzip ./sdk135a.zip
          sudo mkdir Steamworks
          sudo mv ./sdk/* ./Steamworks
      - name: Build
        run: sudo sh build_linux-gm1.sh