name: Build

on: [push, workflow_dispatch]

jobs:
  build-linux:
    name: Build for linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Steamworks SDK
        run: |
          sudo curl --fail ${{ secrets.STEAMWORKS_SDK_135A }} --output sdk135a.zip
          sudo unzip sdk135a.zip
          sudo mkdir Steamworks
          sudo mv ./sdk/* ./Steamworks
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: |
          sudo dotnet msbuild ./Steamworks.gml
          sudo sh build_linux-gm1.sh