name: Build

on: [push, workflow_dispatch]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Steamworks SDK
        run: |
          curl -o sdk142.zip "${{ secrets.STEAMWORKS_SDK_142 }}"
          powershell -command "Expand-Archive -Path sdk142.zip -DestinationPath ."
          mkdir Steamworks
          move ./sdk/* ./Steamworks

      - name: Get GmxGen
        run: |
          curl -o GmxGen.exe "${{ secrets.GMXGEN }}"

      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Windows Libs
        run: msbuild . /property:Configuration=Release

      - name: Post Build
        run: |
          .\post_build.bat
          .\GmxGen.exe "Steamworks.gmx\extensions\Steamworks.gml.extension.gmx"
          .\GmxGen.exe "Steamworks_23\extensions\Steamworks_gml\Steamworks_gml.yy"
          .\GmxGen.exe "Steamworks_yy\extensions\Steamworks_gml\Steamworks_gml.yy"
        
      - name: Upload Windows Artifact (GMS1)
        uses: actions/upload-artifact@v2
        with:
          name: Steamworks.gms1.win
          path: ./Steamworks.gmx

      - name: Upload Windows Artifact (GMS2)
        uses: actions/upload-artifact@v2
        with:
          name: Steamworks.gms2.win
          path: ./Steamworks_yy

      - name: Upload Windows Artifact (GMS2.3)
        uses: actions/upload-artifact@v2
        with:
          name: Steamworks.gms23.win
          path: ./Steamworks_23

  build-linux:
    name: Build for Linux
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Steamworks SDK
        run: |
          sudo curl -o sdk135a.zip "${{ secrets.STEAMWORKS_SDK_135A }}"
          sudo unzip sdk135a.zip
          sudo mkdir Steamworks
          sudo mv ./sdk/* ./Steamworks
        
      - name: Prepare source code
        run: sudo cat Steamworks.gml\steam_*.h Steamworks.gml\steam_*.cpp > Steamworks_yy\extensions\Steamworks_gml\Steamworks.gml.cpp

      - name: Build Linux Libs
        run: sh build_linux_gms1.sh
        
      - name: Upload Linux Artifact (GMS1)
        uses: actions/upload-artifact@v2
        with:
          name: Steamworks.gms1.linux
          path: ./Steamworks.gmx

  build-macos-gms1:
    name: Build for MacOS (GMS1)
    needs: build-windows
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Steamworks SDK
        run: |
          sudo curl -o sdk135a.zip "${{ secrets.STEAMWORKS_SDK_135A }}"
          sudo unzip sdk135a.zip
          sudo mkdir Steamworks
          sudo mv ./sdk/* ./Steamworks

      - name: Prepare source code
        run: sudo cat Steamworks.gml\steam_*.h Steamworks.gml\steam_*.cpp > "Steamworks_yy\extensions\Steamworks_gml\Steamworks.gml.cpp

      - name: Build MacOS Libs
        run: sudo sh build_osx_gms1.sh
        
      - name: Upload MacOS Artifact (GMS1)
        uses: actions/upload-artifact@v2
        with:
          name: Steamworks.gms1.macos
          path: ./Steamworks.gmx
  
  build-macos-gms2:
    name: Build for MacOS (GMS2)
    needs: build-windows
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Steamworks SDK
        run: |
          sudo curl -o sdk142.zip "${{ secrets.STEAMWORKS_SDK_142 }}"
          sudo unzip sdk142.zip
          sudo mkdir Steamworks
          sudo mv ./sdk/* ./Steamworks

      - name: Prepare source code
        run: sudo cat Steamworks.gml\steam_*.h Steamworks.gml\steam_*.cpp > Steamworks_yy\extensions\Steamworks_gml\Steamworks.gml.cpp

      - name: Build MacOS Libs
        run: sudo sh build_osx_gms2.sh
        
      - name: Upload MacOS Artifact (GMS2)
        uses: actions/upload-artifact@v2
        with:
          name: Steamworks.gms2.macos
          path: ./Steamworks_yy