name: Build

on: [push, workflow_dispatch]

jobs:
  build-linux:
    name: Build shared libs
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Steamworks SDK
        run: |
          powershell -command "wget --tries=5 --retry-connrefused -output=sdk135a.zip ${{ secrets.STEAMWORKS_SDK_135A }}"
          powershell -command "Expand-Archive -Force sdk135a.zip ."
          mkdir Steamworks
          move ./sdk/* ./Steamworks
      - name: Install MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Build libs
        run: msbuild .\Steamworks.gml\Steamworks.gml.vcxproj